server:
  port: 8080

spring:
  application:
    name: spring-ai-alibaba-graph-chatflow-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
